"""Hiera YAML → Ansible group_vars / host_vars converter."""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


_SECRET_PATTERNS = re.compile(
    r"(password|passwd|secret|token|key|credential|private|api_key)",
    re.IGNORECASE,
)


def _puppet_key_to_ansible(key: str) -> str:
    """Convert Puppet Hiera key to Ansible variable name.

    mymodule::param → mymodule_param
    apache::vhost::docroot → apache_vhost_docroot
    """
    return key.replace("::", "_").replace("-", "_").replace(".", "_")


def _convert_value(key: str, value: Any) -> Any:
    """Convert a Hiera value to Ansible format.

    - undef → omit (represented as None)
    - Secret-looking values → vault placeholder
    - Puppet boolean strings → Python bool
    """
    if value is None:
        return None

    if isinstance(value, str):
        if value.lower() == "undef":
            return None
        if _SECRET_PATTERNS.search(key):
            vault_var = f"vault_{_puppet_key_to_ansible(key)}"
            return f"{{{{ {vault_var} }}}}"
        return value

    if isinstance(value, dict):
        return {_puppet_key_to_ansible(k): _convert_value(k, v) for k, v in value.items()}

    if isinstance(value, list):
        return [_convert_value(key, item) for item in value]

    return value


class HieraConverter:
    """Converts a Hiera data directory to Ansible group_vars/host_vars."""

    def convert_dir(self, hiera_dir: Path, output_dir: Path) -> list[Path]:
        """Recursively convert all YAML files in a Hiera data directory."""
        written: list[Path] = []
        yaml_files = list(hiera_dir.rglob("*.yaml")) + list(hiera_dir.rglob("*.yml"))

        for yaml_file in sorted(yaml_files):
            try:
                output_path = self._determine_output_path(yaml_file, hiera_dir, output_dir)
                if output_path:
                    result = self._convert_file(yaml_file)
                    output_path.parent.mkdir(parents=True, exist_ok=True)
                    self._write_vars_file(output_path, result, str(yaml_file))
                    written.append(output_path)
            except Exception as exc:
                import logging
                logging.getLogger(__name__).warning("Failed to convert %s: %s", yaml_file, exc)

        return written

    def _determine_output_path(self, yaml_file: Path, hiera_dir: Path, output_dir: Path) -> Path | None:
        """Map a Hiera file path to an Ansible vars file path."""
        rel = yaml_file.relative_to(hiera_dir)
        parts = list(rel.parts)

        if not parts:
            return None

        stem = parts[-1].replace(".yaml", "").replace(".yml", "")

        # nodes/hostname.yaml → host_vars/hostname.yml
        if parts[0] == "nodes":
            hostname = stem
            return output_dir / "host_vars" / hostname / "main.yml"

        # roles/rolename.yaml → group_vars/rolename.yml
        if parts[0] == "roles":
            return output_dir / "group_vars" / f"{stem}.yml"

        # os/osfamily.yaml → group_vars/osfamily.yml
        if parts[0] == "os":
            return output_dir / "group_vars" / f"{stem}.yml"

        # common.yaml → group_vars/all.yml
        if stem in ("common", "global", "all"):
            return output_dir / "group_vars" / "all.yml"

        # Default: group_vars/<stem>.yml
        return output_dir / "group_vars" / f"{stem}.yml"

    def _convert_file(self, yaml_file: Path) -> dict[str, Any]:
        """Convert a single Hiera YAML file to Ansible vars dict."""
        raw = yaml.safe_load(yaml_file.read_text(encoding="utf-8")) or {}
        result: dict[str, Any] = {}

        for key, value in raw.items():
            # Skip Hiera metadata keys
            if key.startswith("__"):
                continue
            ansible_key   = _puppet_key_to_ansible(key)
            ansible_value = _convert_value(key, value)
            if ansible_value is not None:
                result[ansible_key] = ansible_value

        return result

    def _write_vars_file(self, path: Path, data: dict[str, Any], source: str) -> None:
        from datetime import datetime, timezone
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        header = (
            f"# Generated by p2a (Puppet to Ansible Converter)\n"
            f"# Source: {source}\n"
            f"# Date: {ts}\n"
            f"# Review this file — secrets should use ansible-vault\n"
            f"---\n"
        )
        body = yaml.dump(data, default_flow_style=False, allow_unicode=True, sort_keys=True)
        path.write_text(header + body, encoding="utf-8")
